name: three_stage_challenge
description: A simple 3-stage challenge demo app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/stages.json
